### ISSUE TITLE
open in iTerm.app instead of Terminal.app

### ISSUE THREAD

**Issue by mariomare22** [oliviernt/my-bitbar-plugins#1]
Hi,

Thanks for your plugin 
ssh-status.1m.sh

is there a way to open the connection using iTerm instead of Terminal?

running on Catalina

regards,

Mario

**Comment by oliviernt** [comment]
Hi @mariomare22 

there possibly is a way to do that by setting the bash param to iTerm.app but I haven't tried it out.

Maybe have a look at the examples on the docs page: https://github.com/matryer/bitbar#plugin-api

Best,

Olivier
